### ISSUE TITLE
pushing link with diff format

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/cocytus#10]
https://en.wikipedia.org/w/index.php?title=Canarian_American&diff=651119337&oldid=651119306

line 12 of crossref_push: https://github.com/notconfusing/cocytus/blob/master/crossref_push.py#L12

instead of 
` article_url = url = "{server_url}/wiki/{safe_title}".format(server_url=server_url, safe_title=safe_title) `
we need something like
https://en.wikipedia.org/wiki/index.php?title=Canarian_American&diff=651119337&oldid=651119306
``` 
diff = rcdict['revision']['new']
oldid = rcdict['revision']['old']
article_url = url = "{server_url}/w/index.php?title={safe_title}&diff={diff}&oldid={oldid}".format(server_url=server_url, safe_title=safe_title, diff=diff, oldid=oldid) ```

**Comment by afandian** [comment]
Why? I disagree. We would like to receive the url of the article not the diff. We will already be receiving the diff number when issue 5 is complete.

**Comment by notconfusing** [comment]
Adding the `?diff=x&oldid=y` parameters shows you both the diff and the full text of the page after the edit, so that seems rather want we want to me. Why select between the diff and the page when you can have both at once.

**Comment by afandian** [comment]
I have a couple of reasons:

1 - It's a question of the identifier of the resource being reported on. We are saying 'the wikipedia article with this identifier was changed'. The place to store the identifier of the change is in the metadata, not in the article identifier. 

2 - We're looking at quite a broad range of alternative citations, of which Wikipedia is one. This stream will feed into a system that accepts notifications from lots of sources and this change would put cocytus data at odds with other data. If this data was sent we would have to add extra processing at the receiving end to convert it into the right format (strip the diff number).

3 - I thought you and Anthony agreed to include this data in arg3 already anyway? Do you think that we shouldn't?

**Comment by difranco** [comment]
On point 3, per Daniel's request in issue 5 I'm including a human-readable timestamp in arg3 of the API call. Let me know if I should change that.

https://github.com/notconfusing/cocytus/issues/5

Back to the original question, we're happy to provide the data in the desired format but it's not yet clear to me at least what format works best for you. Should we change the current practice of using rcdict['revision']['new'] and rcdict['revision']['old'] fields, containing revision numbers?

**Comment by afandian** [comment]
So, we don't need old and new IDs, because (as far as I can tell) you only need to supply the diff ID and wikimedia automatically shows you the diff it introduced. Compare: 

https://en.wikipedia.org/w/index.php?title=Fish&diff=644584048&oldid=643055320

https://en.wikipedia.org/w/index.php?title=Fish&diff=644584048

So, in #5 I was asking to include only the diff id as arg3 (instead of the timestamp). I think that's all that we need to have complete information. Do you agree?

**Comment by difranco** [comment]
You'll now be seeing the new diff id as arg3 (rcdict['revision']['new'])
[master 0736b40] change arg3 to new revision id
