### ISSUE TITLE
WikiSym paper?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [notconfusing/cocytus#12]
What about submitting a WikiSym paper along the lines of the Wikimania submissions?
The deadline for submission has been extended until next Monday (April 13):
http://www.wikisym.org/ .

**Comment by Daniel-Mietchen** [comment]
OK, no answer means no. Closing now.

**Comment by difranco** [comment]
Yeah, I was away in Utah and missed this.
I think @notconfusing had some other ideas on places to present though.

**Comment by notconfusing** [comment]
Submitted to Wikimania 15. But that seems do be another case of
no-answer-no-acceptance.
