### ISSUE TITLE
Trailing characters in listed DOIs

### ISSUE THREAD

**Issue by Daniel-Mietchen** [notconfusing/cocytus#3]
There are a number of cases where the extraction of the DOI is incomplete, leaving some trailing characters, e.g.

```10.1111/tpj.12145/abstract``` 	2015-02-20 	Wikipedia Cocytus 	Action	add 	Page URL	http://en.wikipedia.org/wiki/Flagellum 	Timestamp	1424475490

```10.1093/emboj/16.11.3219/full``` 	2015-02-20 	Wikipedia Cocytus 	Action	remove 	Page URL	http://en.wikipedia.org/wiki/User%3AOlaneli/sandbox 	Timestamp	1424472621

```10.1099/ijs.0.025098-0\n``` 	2015-02-20 	Wikipedia Cocytus 	Action	add 	Page URL	http://en.wikipedia.org/wiki/Template%3ACite%20pmid/20639229 	Timestamp	1424470143

```10.1002/14356007.a04_011.pub2</ref>``` 	2015-02-21 	Wikipedia Cocytus 	Action	add 	Page URL	http://el.wikipedia.org/wiki/%CE%9F%CE%BE%CE%B5%CE%AF%CE%B4%CE%B9%CE%BF%20%CF%84%CE%BF%CF%85%20%CE%B2%CE%B7%CF%81%CF%85%CE%BB%CE%BB%CE%AF%CE%BF%CF%85 	Timestamp	1424478430

**Comment by notconfusing** [comment]
I know how to fix this issue we just have to use https://github.com/halfak/Extract-scholarly-article-citations-from-Wikipedia/blob/master/mwcites/extractors/doi.py

**Comment by difranco** [comment]
Switched to mwcites.
