### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by Daniel-Mietchen** [notconfusing/cocytus#4]
The following entry suggests that the DOI ```10.1080/02688690701447420``` has been added to http://en.wikipedia.org/wiki/Blood%E2%80%93cerebrospinal%20barrier , but this is (and was) a redirect, and the DOI is actually used in the redirect's target, https://en.wikipedia.org/wiki/Choroid_plexus .

10.1080/02688690701447420 	2015-02-21 	Wikipedia Cocytus 	Action	add 	Page URL	http://en.wikipedia.org/wiki/Blood%E2%80%93cerebrospinal%20barrier 	Timestamp	1424486438

**Comment by notconfusing** [comment]
Ah, yes, I follow the redirect in code, but don't report that I do. Ok, good point.

**Comment by notconfusing** [comment]
@difranco the magic happens on line 19, but is not reported, a simple enough fix

https://github.com/notconfusing/cocytus/blob/master/compare_change.py#L19

**Comment by difranco** [comment]
added a 'redirect' entry in the changes dictionary which appears and contains the title of the page redirected from in the case of a redirect.

**Comment by difranco** [comment]
[master bb7e304] add indication of redirect source in case of redirect
