### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by Daniel-Mietchen** [notconfusing/cocytus#5]
Time stamps in Unix epoch time are not very human readable, nor do they clearly link to the actual version of the wiki page. So what about using the respective oldid and its human-readable timestamp (in UTC) instead or in addition?

**Comment by afandian** [comment]
Did you read my mind?
Agreed, having an actual revision id would be very useful. In the CrossRef Labs Events interface we store the time that the event was sent, so although the time stamp is interesting, the revision id would let us link directly to the diff. Here's how it's currently shown:
http://events.labs.crossref.org/events/types/WikipediaCitation

**Comment by difranco** [comment]
Revision ID is in the posted dictionary under the revision key, example:

```
u'revision': {u'new': 41536316, u'old': 41536282}
```

in

```
{u'comment': u'/* Milare Advogados */', u'wiki': u'ptwiki', u'type': u'edit', u'server_name': u'pt.wikipedia.org', u'server_script_path': u'/w', u'timestamp': 1426029911, u'title': u'Wikip\xe9dia:Pedidos/Bloqueio', u'namespace': 4, u'server_url': u'http://pt.wikipedia.org', u'length': {u'new': 178334, u'old': 178241}, u'user': u'DARIO SEVERI', u'patrolled': True, u'bot': False, u'id': 55699484, u'minor': False, u'revision': {u'new': 41536316, u'old': 41536282}}
```

Just modified to add a human readable time in the 'time' field in the changes in commit ad8a4f0.

**Comment by afandian** [comment]
Can you send this as `arg3` to CrossRef API instead of the timestamp?

**Comment by difranco** [comment]
yup. same string format?

**Comment by afandian** [comment]
Yes a string please.

**Comment by difranco** [comment]
changed unix timestamp to time string in api call
4045022..6a171ed  master -> master
