### ISSUE TITLE
Scrambled DOI

### ISSUE THREAD

**Issue by Daniel-Mietchen** [notconfusing/cocytus#8]
```
10.2/3'\n|-\n| 	2015-03-03 	Wikipedia Cocytus 	

Action
    add
Page URL
    http://it.wikibooks.org/wiki/Disposizioni%20foniche%20di%20organi%20a%20canne/Europa/Italia/Veneto/Provincia%20di%20Padova/Rubano/Sarmeola%20-%20Chiesa%20dell%27Opera%20della%20Provvidenza%20di%20Sant%27%20Antonio
Timestamp
    1425385978
Title
    Disposizioni foniche di organi a canne/Europa/Italia/Veneto/Provincia di Padova/Rubano/Sarmeola - Chiesa dell'Opera della Provvidenza di Sant' Antonio
Wiki
    it.wikibooks.org 
```

**Comment by Daniel-Mietchen** [comment]
What about using CrossRef to check whether anything that Cocytus identifies as a potential DOI is actually one? That would also help solve #3.

Pinging @afandian .

**Comment by difranco** [comment]
We'll have a look at the means to do that. It will add another set of network round-trips so might somewhat reduce performance but we're not spending a lot of time as it is so this should continue to fit within modest resources.

**Comment by difranco** [comment]
We've switched to a better parser so we'll revisit the checking with crossref question if the new parser isn't sufficient to address this.
