### ISSUE TITLE
heartbeat regularity

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/cocytus#9]
assert that heartbeats are being generated and sent at a constant intervals

**Comment by difranco** [comment]
Logs confirm that heartbeats are enqueued at regular intervals of 10 minutes, however they must then be pulled by a worker and re-enqueued for output before they are transmitted to crossref api.

This ensures each message is evidence of end-to-end system funtionality but does not assure regularity in when they are transmitted if queue latency is significant. Until recently we were running with insufficient workers creating a slight queue backlog. Running with sufficient workers to keep the queue close to empty should resolve this.

Alternatives to explore beyond that are to include and take account of on the receiving end an explicit generation time in the heartbeat message (simple) and having the output process try to check on the status of other processes and generate the heartbeats itself based on that (more complex but most flexible).

**Comment by difranco** [comment]
To help begin to address this better, I've added a "heartbeat-type" field to the heartbeat json which indicates either "input" or "output"
Output heartbeats do not go through the queue so they will indicate just that the output process is running, not that the service is running end to end, but they should arrive regularly.
Input heartbeats, as before, go through the whole pipeline so they will not arrive as regularly but do provide clear evidence of end-to-end functionality.

**Comment by difranco** [comment]
[master 241d870] add output heartbeat
